### ISSUE TITLE
VLDTextField character limit doesn't work with initWithCoder

### ISSUE THREAD

**Issue by victormarcias** [Streetmage/ValidationKit#1]
Hi, the setCharactersLimitAndUseForCompare doesn't work if you create the **VLDTextField** by NIB because it doesn't call _onTextFieldDidChange_.
The _UIControlEventEditingChanged_ event is only listened when created with _initWithFrame_.
You need to implement the same stuff that's in the _initWithFrame_ in the _initWithCoder_
Thanks

**Comment by Streetmage** [comment]
@victormarcias Please, check out the 0.0.7 version. Added |setup| method call both for |initWithFrame| and |initWithCoder| initialisers.

**Comment by victormarcias** [comment]
Nice, thanks.
